version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - proxy
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

networks:
  proxy:
    external: true
