version: "3.9"
service:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    deploy:
      resources:
        limites:
          cpus: "0.1"
          memory: 50M
      mode: replicated
      replicas: 1
