version: "3.9"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      mode: replicated
      replicas: 1
