version: '3'
services:
  Portainer:
    image: "cr.portainer.io/portainer/portainer-ce"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.routers.portainer.rule=${PORTAINER_RULES:Host(`portainer.local`)}
        - traefik.http.services.portainer.loadbalancer.server.port=9000
        - traefik.http.routers.portainer.tls=${PORTAINER_TLS:true}
        - traefik.http.routers.portainer.entrypoints=${PORTAINER_ENTRYPOINTS:websecure}
      placement:
        constraints:
          - node.hostname==${NODE_HOSTNAME}
networks:
  proxy:
    external: true
