version: '3'
services:
  Portainer:
    container_name: Portainer
    image: "cr.portainer.io/portainer/portainer-ce"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    privileged: true
    ports:
      - "8000:8000"
      - "9443:9443"
    deploy:
      placement:
        constraints:
          - node.hostname==${NODE_HOSTNAME}
