version: '3.8'

services:
  traefik:
    image: traefik:v3.2.1
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /traefik.yml:/etc/traefik/traefik.yml:ro
      - /dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /run/secrets/wildcard.g.mhl.sh.pem:/etc/traefik/certs/_wildcard.g.mhl.sh.pem:ro
      - /run/secrets/wildcard.g.mhl.sh-key.pem:/etc/traefik/certs/_wildcard.g.mhl.sh.key:ro
    networks:
      - proxy
    environment:
      - NAMECOM_USERNAME=joshgdovin@gmail.com
      - NAMECOM_API_TOKEN=46edc67e281dcb7be4835c6303011e45a69c5353
      - NAMECOM_SERVER=api.name.com
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.rule=Host(`traefik.home.justjosh.us`) || Host(`traefik.local.justjosh.us`)
        - traefik.http.routers.traefik.entrypoints=web
        - traefik.http.middlewares.traefik.forwardauth.trustForwardHeader=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
networks:
  proxy:
    external: true

