version: '3.8'

services:
  pihole:
    image: pihole/pihole
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      - '0.0.0.0:67:67/udp'
      - '0.0.0.0:8053:80/tcp'
    environment:
      - TZ=${PIHOLE_TIMEZONE:'America/Denvor'}
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.services.pihole.loadbalancer.server.port=${PIHOLE_PORT:80}
        - traefik.http.routers.pihole.rule=${PIHOLE_RULES:Host(`pihole.local`)}
        - traefik.http.routers.piehole.entrypoints=${PIHOLE_ENTRYPOINTS:web}
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
networks:
  proxy:
    external: true
